In [1]:
import pandas as pd
import os,sys
from pathlib import Path

In [2]:
output_dir = "/share/home/wyz/Project/result/2025/202506/20250606_3_cibersortx_immune_cell/20250606_24_MDS_sAML_AML_immune_mutation_cell_kmean_merge"

In [3]:
## input

In [3]:
mutation_f  = "/share/home/wyz/Project/result/2025/202506/20250606_3_cibersortx_immune_cell/20250606_9_MDS_sAML_AML_Immune_cor_cell_kmean_and_clin/20250606_1_stat_df_chisq_results_mutation.xls"

In [4]:
mutation_df =  pd.read_csv(mutation_f,sep="\t")
mutation_df

                                p_value  statistic  df
kmean_k4_mark_vs_ASXL1_mut     0.005997  13.805149 NaN
kmean_k4_mark_vs_ASXL2_mut     0.230385   6.484914 NaN
kmean_k4_mark_vs_BCOR_mut      0.000500  51.460303 NaN
kmean_k4_mark_vs_CBL_mut       0.056972  12.584780 NaN
kmean_k4_mark_vs_CREBBP_mut    0.000500  43.439462 NaN
kmean_k4_mark_vs_CSF3R_mut     0.361819   3.027527 NaN
kmean_k4_mark_vs_DNMT3A_mut    0.025987   9.468064 NaN
kmean_k4_mark_vs_EZH2_mut      0.061969   7.359215 NaN
kmean_k4_mark_vs_FLT3_mut      0.001000  22.352576 NaN
kmean_k4_mark_vs_FLT3.ITD_mut  0.311844   3.594373 NaN
kmean_k4_mark_vs_GATA2_mut     0.387806   2.218271 NaN
kmean_k4_mark_vs_IDH1_mut      0.064968   6.869935 NaN
kmean_k4_mark_vs_IDH2_mut      0.931534   0.540042 NaN
kmean_k4_mark_vs_JAK2_mut      0.437281   2.254886 NaN
kmean_k4_mark_vs_KIT_mut       0.024488  10.107443 NaN
kmean_k4_mark_vs_KMT2A_mut     0.110445   7.249938 NaN
kmean_k4_mark_vs_KRAS_mut      0.000500  39.291885 NaN
kmean_k4_mark_vs_NF1_mut       0.670665   1.282332 NaN
kmean_k4_mark_vs_NPM1_mut      0.003498  15.486932 NaN
kmean_k4_mark_vs_NRAS_mut      0.001000  27.980734 NaN
kmean_k4_mark_vs_PHF6_mut      0.777611   1.275997 NaN
kmean_k4_mark_vs_PTPN11_mut    0.007996  14.700383 NaN
kmean_k4_mark_vs_RAD21_mut     0.040480   8.440939 NaN
kmean_k4_mark_vs_RUNX1_mut     0.002499  15.260489 NaN
kmean_k4_mark_vs_SF3B1_mut     0.001999  16.637725 NaN
kmean_k4_mark_vs_SMC1A_mut     0.320340   3.334423 NaN
kmean_k4_mark_vs_SMC3_mut      0.832084   0.829424 NaN
kmean_k4_mark_vs_SPI1_mut      1.000000   0.540373 NaN
kmean_k4_mark_vs_SRSF2_mut     0.043978   8.228603 NaN
kmean_k4_mark_vs_STAG2_mut     0.853573   0.823395 NaN
kmean_k4_mark_vs_TET2_mut      0.011994  11.207999 NaN
kmean_k4_mark_vs_TP53_mut      0.000500  28.606279 NaN
kmean_k4_mark_vs_U2AF1_mut     0.278361   3.829426 NaN
kmean_k4_mark_vs_WT1_mut       0.521739   2.218740 NaN
kmean_k4_mark_vs_ZRSR2_mut     0.009995  12.508014 NaN
kmean_k4_mark_vs_DNMT3A_R882   0.607696   1.950758 NaN
kmean_k4_mark_vs_FLT3_D835     0.025487   8.263146 NaN
kmean_k4_mark_vs_FLT3_TKD      0.000500  58.282874 NaN

In [5]:
merge_df = mutation_df

In [6]:
# 行索引转为第一列，并命名为 Group
merge_df.reset_index(inplace=True)
merge_df.rename(columns={"index":"Group"},inplace=True)
merge_df

                            Group   p_value  statistic  df
0      kmean_k4_mark_vs_ASXL1_mut  0.005997  13.805149 NaN
1      kmean_k4_mark_vs_ASXL2_mut  0.230385   6.484914 NaN
2       kmean_k4_mark_vs_BCOR_mut  0.000500  51.460303 NaN
3        kmean_k4_mark_vs_CBL_mut  0.056972  12.584780 NaN
4     kmean_k4_mark_vs_CREBBP_mut  0.000500  43.439462 NaN
5      kmean_k4_mark_vs_CSF3R_mut  0.361819   3.027527 NaN
6     kmean_k4_mark_vs_DNMT3A_mut  0.025987   9.468064 NaN
7       kmean_k4_mark_vs_EZH2_mut  0.061969   7.359215 NaN
8       kmean_k4_mark_vs_FLT3_mut  0.001000  22.352576 NaN
9   kmean_k4_mark_vs_FLT3.ITD_mut  0.311844   3.594373 NaN
10     kmean_k4_mark_vs_GATA2_mut  0.387806   2.218271 NaN
11      kmean_k4_mark_vs_IDH1_mut  0.064968   6.869935 NaN
12      kmean_k4_mark_vs_IDH2_mut  0.931534   0.540042 NaN
13      kmean_k4_mark_vs_JAK2_mut  0.437281   2.254886 NaN
14       kmean_k4_mark_vs_KIT_mut  0.024488  10.107443 NaN
15     kmean_k4_mark_vs_KMT2A_mut  0.110445   7.249938 NaN
16      kmean_k4_mark_vs_KRAS_mut  0.000500  39.291885 NaN
17       kmean_k4_mark_vs_NF1_mut  0.670665   1.282332 NaN
18      kmean_k4_mark_vs_NPM1_mut  0.003498  15.486932 NaN
19      kmean_k4_mark_vs_NRAS_mut  0.001000  27.980734 NaN
20      kmean_k4_mark_vs_PHF6_mut  0.777611   1.275997 NaN
21    kmean_k4_mark_vs_PTPN11_mut  0.007996  14.700383 NaN
22     kmean_k4_mark_vs_RAD21_mut  0.040480   8.440939 NaN
23     kmean_k4_mark_vs_RUNX1_mut  0.002499  15.260489 NaN
24     kmean_k4_mark_vs_SF3B1_mut  0.001999  16.637725 NaN
25     kmean_k4_mark_vs_SMC1A_mut  0.320340   3.334423 NaN
26      kmean_k4_mark_vs_SMC3_mut  0.832084   0.829424 NaN
27      kmean_k4_mark_vs_SPI1_mut  1.000000   0.540373 NaN
28     kmean_k4_mark_vs_SRSF2_mut  0.043978   8.228603 NaN
29     kmean_k4_mark_vs_STAG2_mut  0.853573   0.823395 NaN
30      kmean_k4_mark_vs_TET2_mut  0.011994  11.207999 NaN
31      kmean_k4_mark_vs_TP53_mut  0.000500  28.606279 NaN
32     kmean_k4_mark_vs_U2AF1_mut  0.278361   3.829426 NaN
33       kmean_k4_mark_vs_WT1_mut  0.521739   2.218740 NaN
34     kmean_k4_mark_vs_ZRSR2_mut  0.009995  12.508014 NaN
35   kmean_k4_mark_vs_DNMT3A_R882  0.607696   1.950758 NaN
36     kmean_k4_mark_vs_FLT3_D835  0.025487   8.263146 NaN
37      kmean_k4_mark_vs_FLT3_TKD  0.000500  58.282874 NaN

In [7]:

def mark_p_value(row):
    if row['p_value'] <= 0.001:
        return "***"
    elif row['p_value'] <= 0.01:
        return "**"
    elif row['p_value'] <= 0.05:
        return "*"
    else:
        return "NS."
 
merge_df['p_value_mark'] = merge_df.apply(mark_p_value, axis=1)
merge_df

                            Group   p_value  statistic  df p_value_mark
0      kmean_k4_mark_vs_ASXL1_mut  0.005997  13.805149 NaN           **
1      kmean_k4_mark_vs_ASXL2_mut  0.230385   6.484914 NaN          NS.
2       kmean_k4_mark_vs_BCOR_mut  0.000500  51.460303 NaN          ***
3        kmean_k4_mark_vs_CBL_mut  0.056972  12.584780 NaN          NS.
4     kmean_k4_mark_vs_CREBBP_mut  0.000500  43.439462 NaN          ***
5      kmean_k4_mark_vs_CSF3R_mut  0.361819   3.027527 NaN          NS.
6     kmean_k4_mark_vs_DNMT3A_mut  0.025987   9.468064 NaN            *
7       kmean_k4_mark_vs_EZH2_mut  0.061969   7.359215 NaN          NS.
8       kmean_k4_mark_vs_FLT3_mut  0.001000  22.352576 NaN          ***
9   kmean_k4_mark_vs_FLT3.ITD_mut  0.311844   3.594373 NaN          NS.
10     kmean_k4_mark_vs_GATA2_mut  0.387806   2.218271 NaN          NS.
11      kmean_k4_mark_vs_IDH1_mut  0.064968   6.869935 NaN          NS.
12      kmean_k4_mark_vs_IDH2_mut  0.931534   0.540042 NaN          NS.
13      kmean_k4_mark_vs_JAK2_mut  0.437281   2.254886 NaN          NS.
14       kmean_k4_mark_vs_KIT_mut  0.024488  10.107443 NaN            *
15     kmean_k4_mark_vs_KMT2A_mut  0.110445   7.249938 NaN          NS.
16      kmean_k4_mark_vs_KRAS_mut  0.000500  39.291885 NaN          ***
17       kmean_k4_mark_vs_NF1_mut  0.670665   1.282332 NaN          NS.
18      kmean_k4_mark_vs_NPM1_mut  0.003498  15.486932 NaN           **
19      kmean_k4_mark_vs_NRAS_mut  0.001000  27.980734 NaN          ***
20      kmean_k4_mark_vs_PHF6_mut  0.777611   1.275997 NaN          NS.
21    kmean_k4_mark_vs_PTPN11_mut  0.007996  14.700383 NaN           **
22     kmean_k4_mark_vs_RAD21_mut  0.040480   8.440939 NaN            *
23     kmean_k4_mark_vs_RUNX1_mut  0.002499  15.260489 NaN           **
24     kmean_k4_mark_vs_SF3B1_mut  0.001999  16.637725 NaN           **
25     kmean_k4_mark_vs_SMC1A_mut  0.320340   3.334423 NaN          NS.
26      kmean_k4_mark_vs_SMC3_mut  0.832084   0.829424 NaN          NS.
27      kmean_k4_mark_vs_SPI1_mut  1.000000   0.540373 NaN          NS.
28     kmean_k4_mark_vs_SRSF2_mut  0.043978   8.228603 NaN            *
29     kmean_k4_mark_vs_STAG2_mut  0.853573   0.823395 NaN          NS.
30      kmean_k4_mark_vs_TET2_mut  0.011994  11.207999 NaN            *
31      kmean_k4_mark_vs_TP53_mut  0.000500  28.606279 NaN          ***
32     kmean_k4_mark_vs_U2AF1_mut  0.278361   3.829426 NaN          NS.
33       kmean_k4_mark_vs_WT1_mut  0.521739   2.218740 NaN          NS.
34     kmean_k4_mark_vs_ZRSR2_mut  0.009995  12.508014 NaN           **
35   kmean_k4_mark_vs_DNMT3A_R882  0.607696   1.950758 NaN          NS.
36     kmean_k4_mark_vs_FLT3_D835  0.025487   8.263146 NaN            *
37      kmean_k4_mark_vs_FLT3_TKD  0.000500  58.282874 NaN          ***

In [8]:
output_f = os.path.join(output_dir, "20250606_21_MDS_sAML_AML_immune_chisq_cell_kmean_merge_vs_mutation_stat.xls")
merge_df.to_csv(output_f,index = False)